# -*- coding: utf-8 -*-
"""Processing_Data_Text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JgVdOUIC0--GgjV2N8AkGaw07-2PYDfQ
"""

import math
import pandas as pd
import numpy as np

# Dokumen 1: Sistem Deteksi Intrusi
document1 = {
    'data': 5, 'serangan': 5, 'sistem': 9, 'deteksi': 4, 'intrusi': 4, 'jaringan': 5,
    'pola': 6, 'normal': 3, 'model': 3, 'otomatis': 3, 'real-time': 2, 'support': 2,
    'vector': 1, 'machine': 1, 'metode': 2, 'klasifikasi': 2, 'audit': 2, 'lalu': 3,
    'lintas': 3, 'probe': 1, 'dos': 1, 'rekaman': 1, 'paket': 2, 'tshark': 1,
    'akurasi': 1, 'false': 1, 'positive': 1, 'administrator': 1
}

# Dokumen 2: Augmentasi Data untuk Deteksi Objek Drone
document2 = {
    'data': 11, 'augmentasi': 8, 'drone': 8, 'algoritma': 4, 'objek': 5, 'penelitian': 4,
    'citra': 3, 'deteksi': 7, 'teknologi': 2, 'deep': 2, 'learning': 2, 'pendeteksian': 3,
    'akurasi': 2, 'menggunakan': 3, 'yolov5': 4, 'hasil': 2, 'meningkatkan': 2,
    'pengaruh': 1, 'metode': 1, 'pengumpulan': 1, 'rotate': 1, 'crop': 1, 'cutout': 1,
    'pelatihan': 2, 'pengujian': 1, 'analisis': 1, 'precision': 1, 'map': 1, 'recall': 1,
    'score': 1, 'konstan': 1, 'hilangnya': 1, 'informasi': 1, 'penting': 1, 'noise': 1,
    'distorsi': 1, 'penerapan': 1, 'utama': 1, 'pemrosesan': 1, 'gambar': 1, 'pengenalan': 1,
    'pola': 1, 'terbatasnya': 1, 'melatih': 1, 'tantangan': 1, 'pengembangan': 1, 'mengevaluasi': 1
}

# Dokumen 3: Deteksi Kesegaran Ikan dengan Deep Learning
document3 = {
    'ikan': 6, 'yolov5': 4, 'dataset': 4, 'aplikasi': 3, 'deep': 2, 'learning': 2,
    'digunakan': 3, 'kesegaran': 3, 'penelitian': 2, 'android': 2, 'gambar': 2,
    'efektif': 2, 'nilai': 3, 'model': 2, 'tingkat': 2, 'uji': 2, 'fase': 2, 'jam': 2,
    'tiga': 2, 'segar': 3, 'faster': 2, 'rcnn': 2, 'precision': 1, 'recall': 1,
    'f1score': 1, 'accuracy': 1, 'map': 1, 'confidence': 1, 'score': 1, 'deteksi': 3,
    'pasar': 2, 'produk': 1, 'kualitas': 1, 'menganalisis': 1,'otomatis': 1, 'akurat': 1,
    'efisiensi': 1, 'implementasi': 2, 'crossvalidation': 1,'metode': 1, 'menunjukkan': 1,
    'ratarata': 1, 'metrik': 2
}

# Mengumpulkan semua abstrak term dari ketiga dokumen
all_terms = sorted(set().union(document1.keys(), document2.keys(), document3.keys()))
print(f"Jumlah total term dari ketiga dokumen: {len(all_terms)}")
print(f"Semua term: {(all_terms)}")

# Buat vektor untuk setiap dokumen
doc1 = [document1.get(term, 0) for term in all_terms]
doc2 = [document2.get(term, 0) for term in all_terms]
doc3 = [document3.get(term, 0) for term in all_terms]

documents = [doc1, doc2, doc3]
N = len(documents)  # Jumlah dokumen = 3

# Hitung TF (Term Frequency)
def compute_tf(doc):
    total_terms = sum(doc)
    return [count / total_terms if total_terms != 0 else 0 for count in doc]

tf_docs = [compute_tf(doc) for doc in documents]

# Hitung DF (Document Frequency - jumlah dokumen yang mengandung term)
df = []
for i in range(len(all_terms)):
    count = sum(1 for doc in documents if doc[i] > 0)
    df.append(count)

# Hitung IDF dengan smoothing
idf = [math.log((N + 1) / (df_i + 1)) + 1 for df_i in df]  # +1 smoothing

# Hitung TF-IDF
tfidf_docs = []
for tf in tf_docs:
    tfidf = [tf[i] * idf[i] for i in range(len(all_terms))]
    tfidf_docs.append(tfidf)

# Fungsi cosine similarity
def cosine_similarity(v1, v2):
    dot = sum(a * b for a, b in zip(v1, v2))
    norm1 = math.sqrt(sum(a * a for a in v1))
    norm2 = math.sqrt(sum(b * b for b in v2))
    return dot / (norm1 * norm2) if norm1 != 0 and norm2 != 0 else 0

# Hitung cosine similarity antar pasangan dokumen
sim_1_2 = cosine_similarity(tfidf_docs[0], tfidf_docs[1])
sim_1_3 = cosine_similarity(tfidf_docs[0], tfidf_docs[2])
sim_2_3 = cosine_similarity(tfidf_docs[1], tfidf_docs[2])

# Tampilkan hasil
print("\n========== HASIL PERHITUNGAN SIMILARITAS KOSINUS ==========")
print(f"Similaritas antara Dokumen 1 dan Dokumen 2 : {sim_1_2:.6f}")
print(f"Similaritas antara Dokumen 1 dan Dokumen 3 : {sim_1_3:.6f}")
print(f"Similaritas antara Dokumen 2 dan Dokumen 3 : {sim_2_3:.6f}")

# Tampilkan matriks similaritas
similarity_matrix = np.array([[1.0, sim_1_2, sim_1_3],
                              [sim_1_2, 1.0, sim_2_3],
                              [sim_1_3, sim_2_3, 1.0]])

print('\n========== MATRIKS SIMILARITAS ==========' )
print(pd.DataFrame(similarity_matrix, columns=['Dokumen 1', 'Dokumen 2', 'Dokumen 3'], index=['Dokumen 1', 'Dokumen 2', 'Dokumen 3']))